name: Demo workflow
on: workflow_dispatch
jobs: 
  print:
    runs-on: macos-latest
    steps:
      - name: Print to console
        run: echo Hello GH actions
      - name: Print a few line
        run: |
          echo First line
          echo Second line
